name: build-win
on:
  push:
    tags: ["v*.*.*"]   
  release:
    types: [published] 

permissions:
  contents: write

jobs:
  win:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps (clean)
        run: npm ci

      - name: Install packager + icon tool
        run: npm i -D electron-packager png-to-ico

    - name: Create ICO from PNG
      run: |
        mkdir build -Force
        npx png-to-ico assets/logo-soumnt.png > build/icon.ico

      - name: Package Windows
        run: npx electron-packager . "Soumnt" --platform=win32 --arch=x64 --out=dist --overwrite --icon=build/icon.ico --asar --asar.unpackDir=resources/bin

      - name: Zip Windows folder
        run: Compress-Archive -Path dist\Soumnt-win32-x64\* -DestinationPath dist\Soumnt-win-x64.zip

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/Soumnt-win-x64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
